### ISSUE TITLE
clobber argument deprecated

### ISSUE THREAD

**Issue by yucelkilic** [jeremiedecock/fits-viewer#1]
Hi,

I got this error when I using the code and changed "clobber" argument with "overwrite" according to reference link below.

https://github.com/jeremiedecock/fits-viewer/blob/fbdc4d82b6e5527c6962ba8681baafb8503fc112/fitsviewer/utils/png2fits.py#L42

Changed in version 1.3: overwrite replaces the deprecated clobber argument.

Ref: http://docs.astropy.org/en/stable/io/fits/api/hdulists.html

**Comment by jeremiedecock** [comment]
Hi,

I fixed it in the repository.

Thanks for your feedback.
